  - name: install systemd timesyncd
    apt:
      name: systemd-timesyncd
      state: present

  - name: start and enable systemd-timesyncd
    ansible.builtin.systemd:
      name: systemd-timesyncd
      state: started
      enabled: yes

  - name: reload systemd
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: restart systemd-timesyncd
    ansible.builtin.systemd:
      name: systemd-timesyncd
      state: restarted

  - name: whait for service to start (30 sec)
    ansible.builtin.wait_for:
      timeout: 30

  - name: install tailscale with script
    shell:  curl -fsSL https://tailscale.com/install.sh | sh

  - name: Remove apt lock files
    file:
      path: "{{ item }}"
      state: absent
    loop:
      - /var/lib/dpkg/lock
      - /var/lib/dpkg/lock-frontend

  - name: install updates
    apt:
      upgrade: dist
      update_cache: yes

  - name: install software (apt)
    apt:
      name:
        - cifs-utils
        - restic
        - zip
        - pipx

  - name: create folder github
    ansible.builtin.file:
      path: /home/ydh/Github
      state: directory
      owner: ydh
      group: ydh
      mode: 0700

  - name: Auto Remove
    ansible.builtin.apt:
      autoremove: yes

  - name: check ssh keys PVEsrv
    stat: 
      path: /home/ydh/.ssh/PVEsrv
    register: check_PVEsrv
  
  - name: gen ssh key PVEsrv
    community.crypto.openssh_keypair:
      comment: YDH-pc
      path: /home/ydh/.ssh/PVEsrv
      type: ed25519
    when: not check_PVEsrv.stat.exists
    # when the file not exists create a key pair

  - name: add ssh client config file
    ansible.builtin.template:
      src: templates/ssh-client-conf.j2
      dest: /home/ydh/.ssh/config

  - name: pipx ensurepath
    shell: pipx ensurepath

  - name: ansible install
    community.general.pipx:
      install_deps: true
      name: ansible


