  - name: limit ssh
    ufw:
      rule: limit
      port: ssh
      proto: tcp

  - name: deny incoming
    ufw:
      default: deny
      direction: incoming

  - name: allow outgoing
    ufw:
      default: allow
      direction: outgoing
  
  - name: reload ufw
    ufw:
      state: reloaded

  - name: enable ufw
    ufw:
      state: enabled