- hosts: backup_server
  become: true
  roles:
  - new_server_install

- hosts: backup_backend
  become: false
  gather_facts: false
  roles:
    - know_hosts

- hosts: backup_targets
  become: false
  gather_facts: false
  roles:
    - know_hosts

- hosts: backup_server
  become: true
  roles: 
  - backupServerInstall

- hosts: backup_server
  become: false
  tasks:
  - name: pull github repo
    git:
      repo: git@github.com:apt-install-ydh/Restic_backup.git
      dest: /tmp/backup
      single_branch: yes
      version: main
      accept_hostkey: true

- hosts: backup_server
  become: true
  tasks:

  - name: copy repo
    copy:
      src: /tmp/backup/
      remote_src: true
      dest: /home/restic/backup/
      owner: restic
      group: restic