- hosts: test
  become: true
  roles:
  - new_server_install

- hosts: backup_backend
  become: false
  gather_facts: false
  roles:
    - know_hosts

- hosts: test
  become: true
  roles: 
  - backupServerInstall

- hosts: test
  become: false
  tasks:
  - name: pull github repo
    git:
      repo: git@github.com:apt-install-ydh/Restic_backup.git
      dest: /tmp/backup
      single_branch: yes
      version: main
      accept_hostkey: true
  