- hosts: ubuntu_vm
  become: true
  tasks:
  - name: import ssh keys ydh
    ansible.builtin.authorized_key:
      user: ydh
      key: '{{ item }}'
    with_file:
      - ssh-keys/YDH-win11-WSL-PVEsrv.pub
      - ssh-keys/YDH-Win11-WSL-PVEsrv2025.pub
