## Home lab maintaince playbook
- hosts: ubuntu_vm
  become: true
  roles:
  - mantaince_base

- hosts: docker
  become: true
  roles:
    - mantaince_docker

- hosts: pi_hole
  become: true
  roles:
   - mantaince_pi-hole 