- hosts: new
  become: true
  tasks:

  - name: update repo and packages (apt)
    apt: 
      upgrade: dist
      update_cache: yes

  - name: autoremove
    ansible.builtin.apt:
      autoremove: yes
