---

- hosts: all
  become: true
  tasks: 
  
  - name: update repo index
    apt:
      update_cache: yes
    when: ansible_distribution == "ubuntu"

  - name: install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "ubuntu"

  - name: install php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "ubuntu"


 - name: update repo index
    DNF:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install apache2 package
    DNF:
      name: httpd
      state: latest
    when: ansible_distribution == "CenOS"

  - name: install php support for apache
    DNF:
      name: php
      state: latest
    when: ansible_distribution == "CentOS"