---

- hosts: PVE
  become: true
  tasks: 
  
  - name: install updates
    tags: updates,always,local
    apt:
      upgrade: dist
      update_cache: yes


  - name: install apache & PHP package
    tags: program,local,apache
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes

  - name: copy defualt html file for site
    tags: apache
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: tailscale
  become: true
  tasks: 
  - name: install mariadb package
    tags: program,tailscale
    apt:
      name: mariadb-server
      state: latest

- hosts: tailscale
  become: true
  tasks:
  - name : install samba
    tags: program,test,tailscale
    package: 
      name: samba
      state: latest


- hosts: tailscale
  become: true
  tasks:
  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root