---

- hosts: new
  become: true
  tasks: 

  - name: install updates
    apt:
      update_cache: yes
    changed_when: false

  - name: install standard programms
    apt:
      name:
        - net-tools
        - unattended-upgrades
        - bsd-mailx
        
  - name: install qemu agent
    apt:
      name:
        - qemu-guest-agent
    when: ansible_virtualization_tech_guest == "Kvm"

  - name: enable & start qemu agent
    tags: qemu
    service: 
      name: qemu-guest-agent
      state: started
      enabled: true
    when: ansible_virtualization_tech_guest == "Kvm"

  - name: show line numbers in nano
    copy:
      src: nano-numbers
      dest: /home/ydh/.nanorc
      owner: root
      group: root
      mode: 0644

  - name: add public keys to ssh file
    ansible.posix.authorized_key:
      user: ydh
      state: present
      key: '{{ item }}'
    with_file:
      - ssh-keys/Ubuntu-Laptop-PVEsrv.pub
      - ssh-keys/YDH-win11-WSL-PVEsrv.pub
      - ssh-keys/AcomLaptop2022PVEsrv.pub

  - name: make firewall policy
    ufw: 
      rule: allow
      port: ssh
      proto: tcp
  
  - name: enable ufw
    ufw:
      state: enabled
      policy: allow
  
  - name: Disable password auth
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PasswordAuthentication'
      line: PasswordAuthentication no

  - name: add ChallengeResponseAuthentication
    lineinfile:
      path: /etc/ssh/sshd_config
      state: present
      regexp: '^ChallengeResponseAuthentication'
      line: ChallengeResponseAuthentication no
  
  - name: Configure unattended-upgrades
    shell: |
      echo "unattended-upgrades unattended-upgrades/enable_auto_updates boolean true" | debconf-set-selections

  - name: Apply unattended-upgrades
    shell: dpkg-reconfigure -f noninteractive --priority=low unattended-upgrades

  - name: configure email address
    lineinfile:
      path: /etc/apt/apt.conf.d/50unattended-upgrades
      state: present
      regexp: '^//Unattended-Upgrade::Mail "";'
      line: Unattended-Upgrade::Mail "ictadmin@yarondeherdt.be"

  - name: add ssh key ansible user
    ansible.builtin.authorized_key:
      user: ansible
      key: '{{ item }}'
    with_file: 
      - ssh-keys/ansible-user.pub