---

- hosts: tailscale
  become: true
  tasks: 

  - name: install updates
    apt:
      update_cache: yes
    changed_when: false

  - name: install standard programms
    apt:
      name:
        - net-tools
        - unattended-upgrades
        
  - name: install qemu agent
    apt:
      name:
        - qemu-guest-agent

  - name: enable & start qemu agent
    service: 
      name: qemu-guest-agent
      state: started
      enabled: true
    when: ansible_system_vendor == "QEMU"

  - name: show line numbers in nano
    copy:
      src: nano-numbers
      dest: /home/ydh/.nanorc
      owner: root
      group: root
      mode: 0644

  - name: add public keys to ssh file
    ansible.posix.authorized_key:
      user: ydh
      state: present
      key: '{{ item }}'
    with_file:
      - ssh-keys/Ubuntu-Laptop-PVEsrv.pub
      - ssh-keys/YDH-win11-WSL-PVEsrv.pub
      - ssh-keys/AcomLaptop2022PVEsrv.pub
  
  - name: add ssh config file
    ansible.builtin.template:
      src: templates/sshd_config_ref.j2
      dest: /etc/ssh/sshd_config

  - name: delete cloud init
    ansible.builtin.file:
      path: /etc/ssh/sshd_config.d/50-cloud-init.conf
      state: absent  
    
  - name: make firewall policy
    ufw: 
      rule: allow
      port: ssh
      proto: tcp
  
  - name: enable ufw
    ufw:
      state: enabled
      policy: allow
   
  - name: Configure unattended-upgrades
    shell: |
      echo "unattended-upgrades unattended-upgrades/enable_auto_updates boolean true" | debconf-set-selections

  - name: Apply unattended-upgrades
    shell: dpkg-reconfigure -f noninteractive --priority=low unattended-upgrades

  - name: add config file unattended-upgrades
    ansible.builtin.template:
      src: templates/50unattended-upgrades.j2
      dest: /etc/apt/apt.conf.d/50unattended-upgrades

  - name: add ssh key ansible user
    ansible.builtin.authorized_key:
      user: ansible
      key: '{{ item }}'
    with_file: 
      - ssh-keys/ansible-user--Ubuntu-laptop.pub
      - ssh-keys/ansible-user--Win11-wsl.pub

  - name: set time zone Europe/Brussels
    community.general.timezone:
      name: Europe/Brussels