# install docker engine
#- name: insall ca-certificates curl
#  apt: 
#    name: ca-certificates curl

- name: Creates directory with permissions
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download docker GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'


- name: permissions
  ansible.builtin.file:
    path: /etc/apt/keyrings/docker.asc
    mode: o=r

- name: add docker repo
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
    mode: '644'

- name: check gpg key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/keyrings/docker.asc

- name: install docker engine
  apt: 
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

- name: Add user to docker group for root use
  user:
    name: ydh
    groups: docker
    append: yes

- name: Enable docker service in systemd
  ansible.builtin.systemd:
    name: docker.service
    enabled: yes

- name: Enable container service in systemd
  ansible.builtin.systemd:
    name: containerd.service
    enabled: yes
